version: "2"

services:
  app:
    build:
      context: "."
    image: $DOCKER_IMAGE
    depends_on:
      - postgres
    environment:
      - CI
      - CODECLIMATE_REPO_TOKEN=efff74f42f6e9dff9daa21e21e8d8d2d3cb33f37b84a9d06bb907edb48a2cf6f
      - DATABASE_URL=postgres://postgres@postgres/active_record-updated_at
      - DOCKER=true
      - RACK_ENV=test
      - RAILS_ENV=test
      - REBUILD_CACHE
    links:
      - postgres
    volumes:
      - .:/app
      - $BUILD_CACHE/bundler:/app/vendor/bundle
      - $BUILD_CACHE/tmp:/app/tmp/cache

  postgres:
    image: lendinghome/postgres:9.4.8

  rubocop:
    image: lendinghome/rubocop
    environment:
      - RUBOCOP_VERSION=2.3
    volumes:
      - .:/app
